export const JOB_INDUSTRIES = [
  "Accounting & Auditing",
  "Administration & Office Support",
  "Advertising & PR",
  "Aerospace & Aviation",
  "Agriculture & Farming",
  "Architecture & Planning",
  "Arts, Media & Entertainment",
  "Automotive",
  "Banking",
  "Beauty & Cosmetics",
  "Biotechnology",
  "Building & Construction",
  "Business Development",
  "Chemical Industry",
  "Civil Engineering",
  "Cleaning & Facilities",
  "Customer Support",
  "Cybersecurity",
  "Data & Analytics",
  "Design (Graphic/UI/UX)",
  "E-commerce",
  "Education & Training",
  "Electrical & Electronics",
  "Energy (Oil, Gas & Renewables)",
  "Engineering (General)",
  "Environmental & Sustainability",
  "Event Management",
  "Fashion & Apparel",
  "Finance & Investment",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Human Resources",
  "Import & Export",
  "Information Technology (IT)",
  "Insurance",
  "Internet & Web Services",
  "Legal",
  "Software Engineer",
  "Logistics & Supply Chain",
  "Manufacturing & Production",
  "Marketing & Growth",
  "Mechanical Engineering",
  "Media & Publishing",
  "Nonprofit & Social Impact",
  "Pharmaceuticals",
  "Product Management",
  "Project Management",
  "Real Estate",
  "Research & Development",
  "Retail",
  "Sales",
  "Science",
  "Security & Law Enforcement",
  "Skilled Trades",
  "Sports & Fitness",
  "Telecommunications",
  "Transportation",
  "Warehousing",
  "Wholesale",
  "Other"
];
